config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "prototypes#index"
  resources :prototypes do
    resources :comments, only: :create
  end
  resources :users, only: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :prototype 
  belongs_to :user  

  validates :text, presence: true
end

app/models/prototype.rb
class Prototype < ApplicationRecord
  with_options presence: true do
    validates :title
    validates :catch_copy
    validates :concept
    validates :image
  end

  belongs_to :user
  has_many :comments, dependent: :destroy
  has_one_attached :image
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name,       presence: true
  validates :profile,    presence: true
  validates :occupation, presence: true
  validates :position,   presence: true

  has_many :prototypes
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!, except:[:index, :show]

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :profile, :occupation, :position])
  end
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.create(comment_params)
    if @comment.save
      redirect_to prototype_path(@comment.prototype)
    else
      @prototype = @comment.prototype
      @comments = @prototype.comments
      render "prototypes/show"
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, prototype_id: params[:prototype_id])
  end
end

app/controllers/prototypes_controller.rb
class PrototypesController < ApplicationController
before_action :set_prototype, only: [:edit, :show, :destroy]

  def index
    @prototypes = Prototype.includes(:user)
  end

  def new
    @prototype = Prototype.new
  end
  
  def create
    @prototype = Prototype.create(prototype_params)
    if @prototype.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @comment = Comment.new
    @comments = @prototype.comments.includes(:user)
  end
  
  def edit
    @prototype = Prototype.find(params[:id])
    unless user_signed_in? && current_user.id == @prototype.user_id
      redirect_to action: :index
    end
  end

  def update
    @prototype = Prototype.find(params[:id])
    @prototype.update(prototype_params)
    if @prototype.save
      redirect_to prototype_path(@prototype.id)
    else
      render :edit
    end
  end

  def destroy
    prototype = Prototype.find(params[:id])
    prototype.destroy
    redirect_to root_path
  end
  
  
  
  
  private

  def prototype_params
    params.require(:prototype).permit(:title, :catch_copy, :concept, :image).merge(user_id: current_user.id)
  end

  def set_prototype
    @prototype = Prototype.find(params[:id])
  end
  
  

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @name = @user.name 
    @prototypes = @user.prototypes
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/prototypes_helper.rb
module PrototypesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>ProtoSpace</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans+JP:400,700,900&display=swap" rel="stylesheet">
  </head>

  <body>
    <header class="header">
      <div class="inner">
        <div class="nav">
          <div class="nav__left">
            <%= link_to image_tag("logo.png", class: :logo), root_path %>
          </div>
          <% if user_signed_in? %>
            <div class="nav__right"> 
              <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: :nav__logout %>
              <%= link_to "New Proto", new_prototype_path, class: :nav__btn %>
            </div>
          <% else %>
            <div class="nav__right">
              <%= link_to "ログイン", new_user_session_path, class: :nav__btn %>
              <%= link_to "新規登録", new_user_registration_path, class: :nav__btn %>
            </div>
          <% end %>
        </div>
      </div>
    </header>
    <%= yield %>
    <footer class="footer">
      <p class="copyright">Copyright © PROTO SPACE All rights reserved.</p>
    </footer>
  </body>
</html>

app/views/prototypes/_form.html.erb
<%= form_with model: @prototype, local: true do |f|%>
  <div class="field">
    <%= f.label :title, "プロトタイプの名称" %><br />
    <%= f.text_field :title, id:"prototype_title" %>
  </div>

  <div class="field">
    <%= f.label :catch_copy, "キャッチコピー" %><br />
    <%= f.text_area :catch_copy, class: :form__text, id:"prototype_catch_copy" %>
  </div>

  <div class="field">
    <%= f.label :concept, "コンセプト" %><br />
    <%= f.text_area :concept, class: :form__text, id:"prototype_concept" %>
  </div>

  <div class="field">
    <%= f.label :image, "プロトタイプの画像" %><br />
    <%= f.file_field :image, id:"prototype_image" %>
  </div>

  <div class="actions">
    <%= f.submit "保存する", class: :form__btn  %>
  </div>
<% end %>

app/views/prototypes/_prototype.html.erb
<div class="card">
  <%= link_to image_tag( prototype.image, class: :card__img ), prototype_path(prototype.id) %>
  <div class="card__body">
    <%= link_to prototype_path(prototype.id), class: :card__title do %>
      <p><%= prototype.title %></p>
    <% end %>
    <p class="card__summary">
      <%= prototype.catch_copy %>
    </p>
    <%= link_to "/users/#{prototype.user.id}", class: :card__user do %>
      <span>by.</span><%= prototype.user.name %>
    <% end %>
  </div>
</div>

app/views/prototypes/edit.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">プロトタイプ編集</h2>
      <%= render partial: 'form' %>
    </div>
  </div>
</div>

app/views/prototypes/index.html.erb
<main class="main">
  <div class="inner">
    <% if user_signed_in? %>
      <div class="greeting">
        <p> こんにちは </p>
        <%= link_to current_user.name , "/users/#{current_user.id}", class: :greeting__link%> <span>さん</span>
      </div> 
    <% end %>
    <div class="card__wrapper">
      <%= render partial: 'prototype', collection: @prototypes %>
    </div>
  </div>
</main>

app/views/prototypes/new.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">新規プロトタイプ投稿</h2>
        <%= render partial: 'form' %>
    </div>
  </div>
</div>

app/views/prototypes/show.html.erb
<main class="main">
  <div class="inner">
    <div class="prototype__wrapper">
      <p class="prototype__hedding">
        <%= @prototype.title %>
      </p>
      <%= link_to "/users/#{@prototype.user.id}", class: :prototype__user do %>
      <span>by.</span><%= @prototype.user.name %>
      <% end %>
      <% if user_signed_in? && current_user.id == @prototype.user_id %>
        <div class="prototype__manage">
          <%= link_to "編集する", edit_prototype_path(@prototype.id), class: :prototype__btn %>
          <%= link_to "削除する", prototype_path(@prototype.id), class: :prototype__btn, method: :delete %>
        </div>
      <% end %>
      <div class="prototype__image">
        <%= image_tag @prototype.image %>
      </div>
      <div class="prototype__body">
        <div class="prototype__detail">
          <p class="detail__title">キャッチコピー</p>
          <p class="detail__message">
            <%= @prototype.catch_copy %>
          </p>
        </div>
        <div class="prototype__detail">
          <p class="detail__title">コンセプト</p>
          <p class="detail__message">
            <%= @prototype.concept %>
          </p>
        </div>
      </div>
      <div class="prototype__comments">
        <% if user_signed_in? %>
          <%= form_with(model: [@prototype, @comment],local: true) do |f| %>
            <div class="field">
              <%= f.label :text, "コメント" %><br />
              <%= f.text_field :text, id:"comment_text" %>
            </div>
            <div class="actions">
              <%= f.submit "送信する", class: :form__btn  %>
            </div>
          <% end %>
        <% end %> 
        <ul class="comments_lists">
            <li class="comments_list">
              <% @comments.each do |comment| %>
                <p>
                  <%= link_to comment.user.name, "/users/#{comment.user_id}", class: :comment_user %>
                  <%= comment.text %>
                </p>
              <% end %>
            </li>
        </ul>
      </div>
    </div>
  </div>
</main>

app/views/users/show.html.erb
<div class="main">
  <div class="inner">
    <div class="user__wrapper">
      <h2 class="page-heading">
        <%= @name %>
      </h2>
      <table class="table">
        <tbody>
          <tr>
            <th class="table__col1">名前</th>
            <td class="table__col2"><%= @name %></td>
          </tr>
          <tr>
            <th class="table__col1">プロフィール</th>
            <td class="table__col2"><%= @user.profile %></td>
          </tr>
          <tr>
            <th class="table__col1">所属</th>
            <td class="table__col2"><%= @user.occupation %></td>
          </tr>
          <tr>
            <th class="table__col1">役職</th>
            <td class="table__col2"><%= @user.position %></td>
          </tr>
        </tbody>
      </table>
      <h2 class="page-heading">
        <%= @name %>さんのプロトタイプ
      </h2>
      <div class="user__card">
        <%= render partial: 'prototypes/prototype', collection: @prototypes %>
      </div>
    </div>
  </div>
</div>